name: Educational Github Action
on: [push]
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run:  docker build -f doc/Dockerfile -t doc-image:latest .
      - 
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{secrets.CR_PAT}}
